### ISSUE TITLE
Noob is getting errors

### ISSUE THREAD

**Issue by ejm554** [parabuzzle/bitbar_metar#1]
I'm new to BitBar, and I'm having trouble with the metar plugin. I'm successfully running a few `.sh` plugins, but errors are displaying with metar. At first I saw an error suggesting that RVM wasn't installed. (Unfortunately, I didn't record the actual text.) After installing RVM, I'm now seeing these errors:

`/Users/<user>/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:54:in 'require': cannot load such file -- bitbar (LoadError)`
`from /Users/<user>/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:54:in 'require'`
`from /Users/<user>/App-Related_Files/BitBar/metar.5m.rb:29:in '<main>'`

I'm a noob when it comes to Ruby, and I admit that I don't really know what I'm doing. I'm also confused about how to follow this instruction within the `metar.5m.rb` file:

`14    # Re-run this script with RVM's default Ruby, after setting up the RVM path,`
`15    # and setting USING_RVM to true, so that this sentry code won't run the second`
`16    # time through.`

I'd appreciate any advice that will help me to resolve this issue.

**Comment by choopes-godaddy** [comment]
Ok, I remember now:

@ejm554, you need to run some commands locally first:

```
sudo gem install bitbar
sudo gem install metar-parser -v 1.4.1
sudo gem install inifile
```

Then, make sure you create the file `~/.bitbarrc` with 
```
[metar]
airport=KBFI
```
or whatever airport.
